### ISSUE TITLE
GlusterFS PersistentVolume 

### ISSUE THREAD

**Issue by raviram203** [HSBawa/icp-ce-on-linux-containers#8]
Sorry to raise another issue, Hari. I thought I had run through these steps a couple of months ago, but I am not sure now. I was trying to compose the PersistentVolume yaml and went into tailspin. I tried the ICP Create PersistentVolume dialog. Does this look correct? Especially `path`:
```
{
  "kind": "PersistentVolume",
  "apiVersion": "v1",
  "metadata": {
    "name": "gfs1-vol2",
    "labels": {}
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "persistentVolumeReclaimPolicy": "Retain",
    "glusterfs": {
      "endpoints": "gluster-cluster",
      "path": "/volume/pool2"
    },
    "capacity": {
      "storage": "10Gi"
    }
  }
}
```
The glusterfs servers volumes seem out of balance. Server 1 shows only five volumes.
```
root@glusterfs-server-1:~# df -h
Filesystem                 Size  Used Avail Use% Mounted on
/dev/sdb1                  280G   41G  236G  15% /
none                       492K     0  492K   0% /dev
udev                        16G     0   16G   0% /dev/fuse
tmpfs                      100K     0  100K   0% /dev/lxd
/dev/sdb2                   96G   60M   91G   1% /share
/dev/sdb8                   96G   62M   91G   1% /volume
tmpfs                      100K     0  100K   0% /dev/.lxd-mounts
tmpfs                       16G   12K   16G   1% /dev/shm
tmpfs                       16G  9.1M   16G   1% /run
tmpfs                      5.0M     0  5.0M   0% /run/lock
tmpfs                       16G     0   16G   0% /sys/fs/cgroup
glusterfs-server-1:/vol3    96G  1.1G   91G   2% /volume/pool3
glusterfs-server-1:/vol2    96G  1.1G   91G   2% /volume/pool2
glusterfs-server-1:/vol7    96G  1.1G   91G   2% /volume/pool7
glusterfs-server-1:/vol6    96G  1.1G   91G   2% /volume/pool6
glusterfs-server-1:/vol10   96G  1.1G   91G   2% /volume/pool10
```
Server 2 shows ten volumes.
```
root@glusterfs-server-2:~# df -h
Filesystem                 Size  Used Avail Use% Mounted on
/dev/sdb1                  280G   40G  236G  15% /
none                       492K     0  492K   0% /dev
udev                        16G     0   16G   0% /dev/fuse
tmpfs                      100K     0  100K   0% /dev/lxd
/dev/sdb2                   96G   60M   91G   1% /share
/dev/sdb9                   96G   62M   91G   1% /volume
tmpfs                      100K     0  100K   0% /dev/.lxd-mounts
tmpfs                       16G   12K   16G   1% /dev/shm
tmpfs                       16G  9.1M   16G   1% /run
tmpfs                      5.0M     0  5.0M   0% /run/lock
tmpfs                       16G     0   16G   0% /sys/fs/cgroup
glusterfs-server-1:/vol1    96G  1.1G   91G   2% /volume/pool1
glusterfs-server-1:/vol7    96G  1.1G   91G   2% /volume/pool7
glusterfs-server-1:/vol3    96G  1.1G   91G   2% /volume/pool3
glusterfs-server-1:/vol8    96G  1.1G   91G   2% /volume/pool8
glusterfs-server-1:/vol2    96G  1.1G   91G   2% /volume/pool2
glusterfs-server-1:/vol5    96G  1.1G   91G   2% /volume/pool5
glusterfs-server-1:/vol4    96G  1.1G   91G   2% /volume/pool4
glusterfs-server-1:/vol10   96G  1.1G   91G   2% /volume/pool10
glusterfs-server-1:/vol6    96G  1.1G   91G   2% /volume/pool6
```

**Comment by HSBawa** [comment]
Hi @raviram203 

I am not sure why gluster volumes seems to be out of balance. I have seen latency in sync process. Can you check logs in /var folder?
Regarding PV, trying /vol2 as path.

**Comment by raviram203** [comment]
hmmmm. Magic. Both glusterfs servers show all ten volumes. I chose /vol2 as the PV target because it was /vol2 was in both servers. Would be nice to verify details of the PV using kubectl. Don't think the create command verifies the presence of usable storage when creating the PV. Any tips?

**Comment by raviram203** [comment]
One more question: Both servers show `glusterfs-server-1:/volNN`. Presume that is by design. Would like to understand (am writing a wiki). And, of course, would like to know if the PV YAML should use `glusterfs-server-1:/vol6` or `/volume/pool6` for `path`.

**Comment by HSBawa** [comment]
@raviram203  
Following steps may provide answer your query (` ... would like to know if the PV YAML should use glusterfs-server-1:/vol6 or /volume/pool6 for path`)

Perform steps 1  (create service) and 2 (create endpoint). Next create a PV using endpoint information (instead of a **specific** GlusterFS server/brick IP) and volume name (ex: /vol1 will be vol1 ...) as path:

1) Create a Service say "hsbawa-glusterfs"
```
  apiVersion: v1
  kind: Service
  metadata:
     name: hsbawa-glusterfs
  spec:
    ports:
    - port: <port number>
```
2) Create Endpoint (name it same as Service above):
In step 1)  we created a Service without a selector, so endpoint will not be created. So now, we create a endpoint and map service and endpoint (same name)
See [reference ](     https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors)

```
apiVersion: v1
kind: Endpoints
metadata:
  name:  hsbawa-glusterfs
subsets:
  - addresses:
      - ip: <IP address of gluster-fs brick1> 
    ports:
      - port: <port number same as one in service>
  - addresses:
      - ip: <IP address of gluster-fs brick2> 
    ports:
      - port: <port number same as one in service>

```

3) Now create a PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs1-vol2
spec:
  capacity:
    storage: 10Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: hsbawa-glusterfs
    path: vol6     #### Not /volume/pool6 or  /vol6
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
```
 
You can also verify the volume name (example using vol6) using following steps:
```
## Make a directory to mount GlusterFS volume.
mkdir -p /mnt/glusterfs/vol
## Mount GlusterFS volume on newly created directory
mount -t glusterfs <GFS BRICK 1 IP>:/vol6 /mnt/glusterfs/vol
## Following 'ls' command will list the volume name (like directory name) and should be 'vol6'.
ls -lZn /mnt/glusterfs/     
```
For more information on PV, you can run command 'kubectl describe pv < pv name > -n < namespace > ' 

Hope this helps.
